Repository mathieupost/SimpleGP, pull requests merged in 2019-06, with the labels that each got.

#8 Early stopping
  cross_validation.py
  simplegp/Weights/Tuner.py
Labels: good first issue, invalid, timo mag niet meedoen

#9 No mutation & Gaussian crossover
  simplegp/Evolution/Evolution.py
  simplegp/Weights/GaussianCrossover.py
  simplegp/Weights/NoMutation.py
  simplegp/Weights/Tuner.py
Labels: bug, super belangrijk

#12 Tune both the offspring and the population in Baldwin mode
  simplegp/Evolution/Evolution.py
  simplegp/Nodes/BaseNode.py
Labels: kasper snapt het niet meer
